project:
  type: website

website:
  title: "Hafsj√≥r"
  site-url: https://heima.hafro.is/~einarhj/hafsjor
  # favicon: "image/hafro_logo.png"
  navbar:
    right:
      - text: Documents
        menu:
          - leaflet.qmd
          - links.qmd
      - icon: github
        href: https://github.com/einarhjorleifsson/hafsjor

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
